baseURL = "https://example.org/"
languageCode = "en"
title = "Material Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_name = "hugo-material-docs"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	search_enabled = true

	[params.feature]
		tabs = true

	[params.logo]
		icon = ""
		image = "images/logo.png"

	[params.palette]
    	primary = "red"
    	accent  = "teal"

  [params.font]
  	text = "Roboto"
  	code = "Roboto Mono"

	[[params.repositories]]
		name = "hugo-material-docs"
		url = "https://github.com/digitalcraftsman/hugo-material-docs"

[social]
	globe		 = "https://www.scopisto.com"
	twitter  = "https://twitter.com/oliemansm"
	github   = "https://github.com/oliemansm"
	linkedin = "https://linkedin.com/in/scopisto"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[outputs]
	home = ["HTML", "RSS", "JSON"]
